package mx.ids.playbit.utils

const val SUCCESS_SCREEN_TYPE = "SUCCESS_SCREEN_TYPE"
const val WARNING_SCREEN_TYPE = "WARNING_SCREEN_TYPE"
const val ERROR_SCREEN_TYPE = "ERROR_SCREEN_TYPE"
const val EXTRA_SCREEN_TYPE = "EXTRA_SCREEN_TYPE"
const val EXTRA_MESSAGE = "EXTRA_MESSAGE"